services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
      MYSQL_BIND_ADDRESS: 0.0.0.0
    command: --sql-mode=""

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: project
    depends_on:
      - mysql
    restart: always  


  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:

